version: '3.8'

services:
  sigma_evolution:
    build: 
      context: ./
      dockerfile: Dockerfile
    command: ./sigma_evolution
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5436:5432"

volumes:
  pgdata: