DROP INDEX IF EXISTS idx_books_name;
DROP INDEX IF EXISTS idx_courses_url;

DROP TABLE IF EXISTS Books CASCADE;
DROP TABLE IF EXISTS Playlists CASCADE;
DROP TABLE IF EXISTS Courses CASCADE;

DROP TABLE IF EXISTS Progress CASCADE;

DROP TABLE IF EXISTS Skill CASCADE;